### ISSUE TITLE
MediatR Features

### ISSUE THREAD

**Issue by JuergenRB** [juro-org/MediatR.LightCore#5]
- [x] Request Handler #1  
- [x] Void Request Handler #1
- [x] Pipeline Behavior #1
- [x] Pre-Processor #6
- [x] Post-Processor #6
- [x] Constrained Post-Processor #6
- [x] Ordered Behaviors #6
- [x] Notification Handler #1
- [x] Notification Handlers #1
- [x]  Constrained Notification Handler #1
- [x] Covariant Notification Handler #7
- [x] Handler for inherited request with same exception used #7
- [ ] Handler for inherited request with base exception used
- [ ] Handler for request with less specific exception used by priority
- [ ] Preferred handler for inherited request with base exception used.
- [x] Overridden handler for inherited request with same exception used #7
